language: ruby

env:
  - global:
    - AWS_REGION=irrelevant
    - DISPLAY=:99.0
    - DYNAMODB_URL=http://localhost:8000

sudo: false

addons:
  firefox: "latest"
  apt:
    packages:
    - awscli

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - wget https://s3.eu-central-1.amazonaws.com/dynamodb-local-frankfurt/dynamodb_local_latest.tar.gz
  - mkdir ddb
  - tar -xvzf dynamodb_local_latest.tar.gz -C ddb
  - java -Djava.library.path=ddb/dynamodb_local/DynamoDBLocal_lib -jar ddb/DynamoDBLocal.jar -sharedDb -inMemory &
  - ./create_table.sh

before_script:
  - firefox --version
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

rvm:
  - 2.3.1
